# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: setup environment
          command: |
            echo 'export PYTHONPATH=~/repo/integrate' >> $BASH_ENV

      - run:
          name: install linters
          command: |
            sudo apt-get install curl
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install nodejs
            sudo npm install -g markdownlint-cli
            sudo npm install -g markdown-spellcheck

      - run:
          name: markdowns
          command: |
            markdownlint *.md
            mdspell --ignore-numbers --ignore-acronyms --report --en-us ./*.md

      - run:
          name: lint the integrator
          command: |
            pipenv run pylint --rcfile=integrate/.pylintrc integrate

      - run:
          name: unit test the integrator
          command: |
            pushd integrate
            pipenv run python test/test_repocompiler.py
            pipenv run python test/test_mdcontentcheck.py
            popd

      - run:
          name: functional test of content
          command: |
            pipenv run python integrate/test/MarkDownsFunctionalTest.py
            pipenv run python integrate/test/SamplesFunctionalTest.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
